In [9]:
import pandas as pd
import numpy as np 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix, f1_score
from imblearn.over_sampling import SMOTE
from imblearn.under_sampling import RandomUnderSampler
from sklearn import svm

In [10]:
data = pd.read_csv("titanic.csv")
data.describe


<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                 

In [11]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [12]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [13]:
data= data.drop(columns="Cabin", axis=1)

In [14]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Embarked  
0      0         A/5 21171   7.2500        S  
1      0          PC 17599  71.2833        C  
2      0  STON/O2. 3101282   7.9250        S  
3      0            113803  53.1000        S  
4      0            373450   8.0500        S

In [15]:
data["Age"].fillna(data["Age"].mode()[0], inplace=True)

C:\Users\faiza\AppData\Local\Temp\ipykernel_120968\939265755.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Age"].fillna(data["Age"].mode()[0], inplace=True)


In [16]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

In [17]:
data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)

C:\Users\faiza\AppData\Local\Temp\ipykernel_120968\3644085981.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  data["Embarked"].fillna(data["Embarked"].mode()[0], inplace=True)


In [18]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [19]:
data.replace({"Sex":{"male":0, "female":1}, "Embarked":{"S":0, "C":1, "Q":2}}, inplace=True)

C:\Users\faiza\AppData\Local\Temp\ipykernel_120968\634892552.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data.replace({"Sex":{"male":0, "female":1}, "Embarked":{"S":0, "C":1, "Q":2}}, inplace=True)


In [20]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name  Sex   Age  SibSp  Parch  \
0                            Braund, Mr. Owen Harris    0  22.0      1      0   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...    1  38.0      1      0   
2                             Heikkinen, Miss. Laina    1  26.0      0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)    1  35.0      1      0   
4                           Allen, Mr. William Henry    0  35.0      0      0   

             Ticket     Fare  Embarked  
0         A/5 21171   7.2500         0  
1          PC 17599  71.2833         1  
2  STON/O2. 3101282   7.9250         0  
3            113803  53.1000         0  
4            373450   8.0500         0

In [21]:
X_train= data.drop(columns=["Name", "Ticket", "Survived"], axis=1)
Y_train= data["Survived"]


In [22]:
X_train.head()

PassengerId  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0            1       3    0  22.0      1      0   7.2500         0
1            2       1    1  38.0      1      0  71.2833         1
2            3       3    1  26.0      0      0   7.9250         0
3            4       1    1  35.0      1      0  53.1000         0
4            5       3    0  35.0      0      0   8.0500         0

In [23]:
Y_train.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [24]:
counts = Y_train.value_counts()
print("Number of 0s (Did not survive):", counts[0])
print("Number of 1s (Survived):", counts[1])

Number of 0s (Did not survive): 549
Number of 1s (Survived): 342


In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X_train,Y_train, test_size=0.2, random_state=42, stratify=Y_train)

In [28]:
Model = RandomForestClassifier(random_state=42)

In [31]:
Model_svm = svm.SVC()

In [29]:
Model.fit(X_train, Y_train)

RandomForestClassifier(random_state=42)

In [32]:
#SVM Model
Model_svm.fit(X_train, Y_train)

SVC()

In [54]:
Y_pred = Model.predict(X_test)
print("Results without balancing:")
print("Accuracy:", round(accuracy_score(Y_test, Y_pred), 3)*100)
print("f1 score is:",f1_score(Y_test, Y_pred)*100)
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred))
print("Classification Report:\n", classification_report(Y_test, Y_pred))

Results without balancing:
Accuracy: 84.6
f1 score is: 78.0
Confusion Matrix:
 [[82  8]
 [14 39]]
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.91      0.88        90
           1       0.83      0.74      0.78        53

    accuracy                           0.85       143
   macro avg       0.84      0.82      0.83       143
weighted avg       0.85      0.85      0.84       143



In [37]:
#Prediction using SVM
Y_pred_svm = Model.predict(X_test)
print("Prediction using SVM Model--------------------\n")
print("Results without balancing:")
print("Accuracy:", round(accuracy_score(Y_test, Y_pred_svm), 3)*100)
print("f1 score is:",f1_score(Y_test, Y_pred_svm)*100)
print("Confusion Matrix:\n", confusion_matrix(Y_test, Y_pred_svm))
print("Classification Report:\n", classification_report(Y_test, Y_pred_svm))

Prediction using SVM Model--------------------

Results without balancing:
Accuracy: 81.6
f1 score is: 74.80916030534351
Confusion Matrix:
 [[97 13]
 [20 49]]
Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.88      0.85       110
           1       0.79      0.71      0.75        69

    accuracy                           0.82       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.82      0.81       179



In [38]:
smote = SMOTE(random_state=42)

In [39]:
X_train_bal, Y_train_bal = smote.fit_resample(X_train, Y_train)

In [40]:
counts = Y_train_bal.value_counts()
print("Number of 0s (Did not survive):", counts[0])
print("Number of 1s (Survived):", counts[1])

Number of 0s (Did not survive): 439
Number of 1s (Survived): 439


In [37]:
Model_bal = RandomForestClassifier(random_state=42)

In [41]:
Model_bal_svm = svm.SVC()

In [39]:
Model_bal.fit(X_train_bal, Y_train_bal)

RandomForestClassifier(random_state=42)

In [42]:
Model_bal_svm.fit(X_train_bal, Y_train_bal)

SVC()

In [40]:
y_pred_bal = Model_bal.predict(X_test)

In [43]:
y_pred_bal_svm = Model_bal_svm.predict(X_test)

In [68]:
print("\nResults with balancing:")
print("Accuracy:", round(accuracy_score(Y_test, y_pred_bal),2)*100)
print("f1 score is:",f1_score(Y_test, y_pred_bal)*100)
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_bal))
print("Classification Report:\n", classification_report(Y_test, y_pred_bal))


Results with balancing:
Accuracy: 78.0
f1 score is: 70.9090909090909
Confusion Matrix:
 [[72 18]
 [14 39]]
Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.80      0.82        90
           1       0.68      0.74      0.71        53

    accuracy                           0.78       143
   macro avg       0.76      0.77      0.76       143
weighted avg       0.78      0.78      0.78       143



In [44]:
print("\nResults with balancing using SVM:\n")
print("Accuracy:", round(accuracy_score(Y_test, y_pred_bal_svm),2)*100)
print("f1 score is:",f1_score(Y_test, y_pred_bal_svm)*100)
print("Confusion Matrix:\n", confusion_matrix(Y_test, y_pred_bal_svm))
print("Classification Report:\n", classification_report(Y_test, y_pred_bal_svm))


Results with balancing using SVM:

Accuracy: 65.0
f1 score is: 35.051546391752574
Confusion Matrix:
 [[99 11]
 [52 17]]
Classification Report:
               precision    recall  f1-score   support

           0       0.66      0.90      0.76       110
           1       0.61      0.25      0.35        69

    accuracy                           0.65       179
   macro avg       0.63      0.57      0.55       179
weighted avg       0.64      0.65      0.60       179



In [45]:
undersampler = RandomUnderSampler(random_state=42)
X_train_under, y_train_under = undersampler.fit_resample(X_train, Y_train)

In [46]:
#prediction using SVM
undersampler_svm = RandomUnderSampler(random_state=42)
X_train_under_svm, y_train_under_svm = undersampler_svm.fit_resample(X_train, Y_train)

In [71]:
counts = y_train_under.value_counts()
print("Number of 0s (Did not survive):", counts[0])
print("Number of 1s (Survived):", counts[1])

Number of 0s (Did not survive): 210
Number of 1s (Survived): 210


In [72]:
clf_under = RandomForestClassifier(random_state=42)
clf_under.fit(X_train_under, y_train_under)

RandomForestClassifier(random_state=42)

In [48]:
#Prediction using SVM
clf_under_svm = svm.SVC()
clf_under_svm.fit(X_train_under_svm, y_train_under_svm)

SVC()

In [73]:
y_pred_under = clf_under.predict(X_test)

In [50]:
#SVM
y_pred_bal_svm = clf_under_svm.predict(X_test)

In [77]:
print("Accuracy (after undersampling):", accuracy_score(Y_test, y_pred_under)*100)
print("Confusion Matrix (after undersampling):\n", confusion_matrix(Y_test, y_pred_under)*100)
print("Classification Report (after undersampling):\n", classification_report(Y_test, y_pred_under))

Accuracy (after undersampling): 83.21678321678321
Confusion Matrix (after undersampling):
 [[7500 1500]
 [ 900 4400]]
Classification Report (after undersampling):
               precision    recall  f1-score   support

           0       0.89      0.83      0.86        90
           1       0.75      0.83      0.79        53

    accuracy                           0.83       143
   macro avg       0.82      0.83      0.82       143
weighted avg       0.84      0.83      0.83       143



In [51]:
print("Prediction using SVM Model--------------------\n")
print("Accuracy (after undersampling using SVM):", accuracy_score(Y_test, y_pred_bal_svm)*100)
print("Confusion Matrix (after undersampling using SVM):\n", confusion_matrix(Y_test, y_pred_bal_svm)*100)
print("Classification Report (after undersampling using SVM):\n", classification_report(Y_test, y_pred_bal_svm))

Prediction using SVM Model--------------------

Accuracy (after undersampling using SVM): 64.80446927374301
Confusion Matrix (after undersampling using SVM):
 [[10200   800]
 [ 5500  1400]]
Classification Report (after undersampling using SVM):
               precision    recall  f1-score   support

           0       0.65      0.93      0.76       110
           1       0.64      0.20      0.31        69

    accuracy                           0.65       179
   macro avg       0.64      0.57      0.54       179
weighted avg       0.64      0.65      0.59       179

